graphhopper:
  datareader.file: {{OSM_FILE}}
  graph.location: graph-cache

  # Importar todas las vias relevantes para el perfil peatonal
  import.osm.ignored_highways: ""

  # Encoded values usados por los custom models y la extraccion de detalles
  graph.encoded_values: road_class,road_environment,max_speed,road_access

  # Perfiles de enrutamiento habilitados
  profiles:
    - name: foot
      transport_mode: foot
      weighting: custom
      custom_model:
        speed:
          - if: true
            limit_to: 4.25  # 5 km/h * 0.85 = 4.25 km/h para accesibilidad
        distance_influence: 70

    - name: car
      transport_mode: car
      weighting: custom
      custom_model:
        speed:
          - if: true
            limit_to: 120  # Limitar a carreteras urbanas/regionales
        distance_influence: 35

    - name: bus
      transport_mode: car
      weighting: custom
      custom_model:
        speed:
          - if: true
            limit_to: 70  # Velocidad maxima tipica de buses urbanos
        priority:
          - if: road_class == MOTORWAY
            multiply_by: 0.7
          - if: road_class == TRUNK
            multiply_by: 0.8
        distance_influence: 45

    - name: pt
      transport_mode: foot
      weighting: custom
      custom_model:
        speed:
          - if: true
            limit_to: 80  # Velocidad maxima para buses/metro

  # Ajustes del motor de transporte publico
  pt:
    enabled: true
    walk_speed: 4.0
    max_transfers: 4

  # Fuente GTFS oficial (WayFindCL sincroniza el mismo feed en DB)
  gtfs:
    file: {{GTFS_FILE}}
    use_transfers_txt: true

  # Optimizaciones
  prepare:
    min_network_size: 200
    min_one_way_network_size: 200

  routing:
    max_visited_nodes: 1000000

# Configuracion del servidor DropWizard
server:
  application_connectors:
    - type: http
      port: 8989
  admin_connectors:
    - type: http
      port: 8990
